// Stable, append-only registries used to compactly encode a round into a
// shareable /round/[code] URL (see game/share/roundCode.ts) — a golfer or
// course's INDEX here is baked into every share link ever generated, so:
//
//   - NEVER reorder an existing entry.
//   - NEVER remove an entry, even if the course/golfer is later cut from
//     countries.json/courses.json — removing one would silently corrupt
//     every share link already generated for it.
//   - Adding a new course or golfer to the real content just means
//     appending its id to the END of the matching list below, in the same
//     commit. It doesn't need to happen atomically with the content
//     change, but do it in the same session so it doesn't get forgotten.
//
// Snapshotted from the real content order as of the courses/golfers that
// existed when share links were first built (session history — see
// PROJECT_CONTEXT.md).
export const COURSE_REGISTRY: readonly string[] = [
  'augusta-national',
  'carnoustie',
  'valderrama',
  'tpc-sawgrass',
  'royal-birkdale',
  'marco-simone',
  'pebble-beach',
  'st-andrews',
  'brabazon',
  'medinah',
  'le-golf-national',
  'earth-course',
]

export const GOLFER_REGISTRY: readonly string[] = [
  'usa-nicklaus',
  'usa-hogan',
  'usa-woods',
  'usa-spieth',
  'usa-thomas',
  'usa-koepka',
  'usa-dechambeau',
  'usa-clark',
  'usa-scheffler',
  'usa-schauffele',
  'usa-fowler',
  'usa-mickelson',
  'usa-couples',
  'sco-old-tom-morris',
  'sco-young-tom-morris',
  'sco-lyle',
  'sco-montgomerie',
  'sco-lawrie',
  'sco-macintyre',
  'rsa-player',
  'rsa-els',
  'rsa-goosen',
  'rsa-oosthuizen',
  'rsa-immelman',
  'rsa-schwartzel',
  'eng-faldo',
  'eng-westwood',
  'eng-rose',
  'eng-fleetwood',
  'eng-poulter',
  'eng-willett',
  'eng-fitzpatrick',
  'eng-hatton',
  'eng-donald',
  'esp-ballesteros',
  'esp-olazabal',
  'esp-garcia',
  'esp-rahm',
  'esp-jimenez',
  'esp-cabrerabello',
  'nir-mcilroy',
  'nir-clarke',
  'nir-mcdowell',
  'nir-daly',
  'nir-hoey',
  'nir-maybin',
  'aus-norman',
  'aus-scott',
  'aus-day',
  'aus-smith',
  'aus-ogilvy',
  'aus-elkington',
  'aus-lee',
  'jpn-aoki',
  'jpn-ozaki',
  'jpn-ishikawa',
  'jpn-matsuyama',
  'jpn-maruyama',
  'jpn-hoshino',
  'swe-stenson',
  'swe-parnevik',
  'swe-noren',
  'swe-lingmerth',
  'swe-lagergren',
  'swe-kinhult',
  'ger-langer',
  'ger-kaymer',
  'ger-cejka',
  'ger-siem',
  'ger-jaeger',
  'ger-paul',
  'irl-harrington',
  'irl-lowry',
  'irl-mcginley',
  'irl-oconnorjr',
  'irl-walton',
  'irl-lawrie',
  'wal-woosnam',
  'wal-dredge',
  'wal-donaldson',
  'wal-llewellyn',
  'wal-manley',
  'wal-davies',
  'nzl-charles',
  'nzl-campbell',
  'nzl-lee',
  'nzl-fox',
  'nzl-nobilo',
  'nzl-turner',
  'can-weir',
  'can-conners',
  'can-hadwin',
  'can-taylor',
  'can-ames',
  'can-hearn',
  'kor-yang',
  'kor-choi',
  'kor-im',
  'kor-kim-siwoo',
  'kor-an',
  'kor-kim-tom',
  'den-bjorn',
  'den-hansen',
  'den-olesen',
  'den-hojgaard-r',
  'den-hojgaard-n',
  'den-bjerregaard',
  'ita-rocca',
  'ita-molinari-f',
  'ita-molinari-e',
  'ita-manassero',
  'ita-migliozzi',
  'ita-paratore',
  'mex-regalado',
  'mex-toledo',
  'mex-ortiz-c',
  'mex-ancer',
  'mex-ortiz-a',
  'mex-diaz',
  'oth-singh',
  'oth-hovland',
  'oth-niemann',
  'oth-colsaerts',
  'oth-price',
  'usa-sarazen',
]
